services:
  streamlit-app:
    restart: always
    depends_on:
      joker:
        condition: service_started
    container_name: streamlit-app
    build:
      context: ./services/streamlit_app
    environment:
      - MODEL_URL=http://joker:8005/generate_joke
    command: streamlit run Main_Page.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - 8501:8501
  joker:
    restart: always
    container_name: joker
    build:
      context: ./services/joker
    env_file: .env
    command: uvicorn joker:app --host 0.0.0.0 --port 8005
    ports:
      - 7777:8005
    