services:
  # streamlit-app:

  joker:
    restart: always
    container_name: joker
    build:
      context: ./services/joker
    env_file: .env
    command: uvicorn joker:app --host 0.0.0.0 --port 8005
    ports:
      - 7777:8005
    